 title: Towards a multi-stakeholder value-based assessment framework for algorithmic systems
 description: Additional material for the paper *Towards a multi-stakeholder value-based assessment framework for algorithmic systems* published at the 2022 ACM Conference on Fairness, Accountability, and Transparency. 
